insert into public.products (id, name, category, price, is_active, image_path) values
('36w-2x2-panel-light', 'Panel Light', 'Smart Lighting', 0, true, 'products/36W 2X2 Panel Light.png'),
('4-touch-basic', '4 Touch-Basic', 'Modular Touch', 0, true, 'products/4 Touch-Basic (6A-Relay).png'),
('4-touch-pro', '4 Touch-Pro ', 'Modular Touch', 0, true, 'products/4 Touch-Pro (10A-Relay & RGB Led).png'),
('4-touch-rf', '4 Touch-RF ', 'Premium Touch', 0, true, 'products/4 Touch-RF (6A-Relay).png'),
('cabinet-lock', 'Cabinet Lock', 'Smart Locks', 0, true, 'products/Cabinet Lock.png'),
('chrome-glass-touch', 'Chrome Glass Touch', 'Premium Touch', 0, true, 'products/Chrome Glass Touch.png'),
('dimmable-cct-36w-2x2-panel-rf', 'Dimmable CCT ', 'Smart Lighting', 0, true, 'products/Dimmable CCT 36W 2X2 Panel RF.png'),
('fan-dimmer-touch-basic', 'Fan Dimmer Touch-Basic (6A-Relay)', 'Modular Touch', 0, false, 'products/Fan Dimmer Touch-Basic (6A-Relay).png'),
('fan-dimmer-touch-pro', 'Fan Dimmer Touch-Pro ', 'Modular Touch', 0, false, 'products/Fan Dimmer Touch-Pro (10A-Relay & RGB Led).png'),
('fan-dimmer-touch-rf', 'Fan Dimmer Touch-RF ', 'Premium Touch', 0, false, 'products/Fan Dimmer Touch-RF (6A-Relay).png'),
('fan-touch-acrylic', 'FAN Touch-Acrylic', 'Premium Touch', 0, true, 'products/FAN Touch-Acryllic.png'),
('full-glass-touch-1-curtain-2m', 'Full Glass Touch 1 Curtain', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 1 Curtain (2M).png'),
('full-glass-touch-10-switch-1-fan-2-socket-12m', 'Full Glass Touch 10 Switch 1 Fan 2 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 10 Switch (1-25A) 1 Fan 2 Socket (2-10A) (12M).png'),
('full-glass-touch-10-switch-1-socket-8m', 'Full Glass Touch 10 Switch 1 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 10 Switch (2-20A) 1 Socket (1-10A) (8M).png'),
('full-glass-touch-10-switch-6m', 'Full Glass Touch 10 Switch ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 10 Switch (2-20A) (6M).png'),
('full-glass-touch-2-switch-1-curtain-2m', 'Full Glass Touch 2 Switch 1 Curtain', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 2 Switch 1 Curtain (2M).png'),
('full-glass-touch-2-switch-1-fan-1-curtain-4m', 'Full Glass Touch 2 Switch 1 Fan 1 Curtain ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 2 Switch 1 Fan 1 Curtain (4M).png'),
('full-glass-touch-2-switch-1-fan-1-socket-6m', 'Full Glass Touch 2 Switch 1 Fan 1 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 2 Switch (1-25A) 1 Fan 1 Socket (1-10A) (6M).png'),
('full-glass-touch-2-switch-1-fan-4m', 'Full Glass Touch 2 Switch 1 Fan', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 2 Switch (1-25A) 1 Fan (2M).png'),
('full-glass-touch-2-switch-2-socket-6m', 'Full Glass Touch 2 Switch 2 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 2 Switch (1-25A) 2 Socket (2-10A) (6M).png'),
('full-glass-touch-2-switch-2m', 'Full Glass Touch 2 Switch ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 2 Switch (1-25A) (2M).png'),
('full-glass-touch-4-switch-1-curtain-4m', 'Full Glass Touch 4 Switch 1 Curtain', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 4 Switch (1-25A) 1 Curtain (4M).png'),
('full-glass-touch-4-switch-1-fan-1-socket-6m', 'Full Glass Touch 4 Switch 1 Fan 1 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 4 Switch 1 Fan 1 Socket (1-10A) (6M).png'),
('full-glass-touch-4-switch-1-fan-4m', 'Full Glass Touch 4 Switch 1 Fan ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 4 Switch 1 Fan (4M).png'),
('full-glass-touch-4-switch-2-fan-1-socket-8m', 'Full Glass Touch 4 Switch 2 Fan 1 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 4 Switch 2 Fan 1 Socket (1-10A) (8M).png'),
('full-glass-touch-4-switch-2-fan-6m', 'Full Glass Touch 4 Switch 2 Fan ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 4 Switch 2 Fan (6M).png'),
('full-glass-touch-4-switch-2-fan-8m', 'Full Glass Touch 4 Switch 2 Fan ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 4 Switch 2 Fan (8M).png'),
('full-glass-touch-4-switch-2-socket-6m', 'Full Glass Touch 4 Switch 2 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 4 Switch 2 Socket (2-10A) (6M).png'),
('full-glass-touch-4-switch-2m', 'Full Glass Touch 4 Switch ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 4 Switch (2M).png'),
('full-glass-touch-6-switch-1-curtain-4m', 'Full Glass Touch 6 Switch 1 Curtain', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 6 Switch (1-25A) 1 Curtain (4M).png'),
('full-glass-touch-6-switch-1-fan-1-socket-8m', 'Full Glass Touch 6 Switch 1 Fan 1 Socket', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 6 Switch (1-25A) 1 Fan 1 Socket (1-10A) (8M).png'),
('full-glass-touch-6-switch-1-fan-6m', 'Full Glass Touch 6 Switch 1 Fan ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 6 Switch (1-25A) 1 Fan (6M).png'),
('full-glass-touch-6-switch-1-fan-8m', 'Full Glass Touch 6 Switch (1-25A) 1 Fan (8M)', 'Full Glass Touch', 0, false, 'products/Full Glass Touch 6 Switch (1-25A) 1 Fan (8M).png'),
('full-glass-touch-6-switch-1-socket-1-curtain-6m', 'Full Glass Touch 6 Switch 1 Socket 1 Curtain ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 6 Switch (1-25A) 1 Socket (1-10A) 1 Curtain (6M).png'),
('full-glass-touch-6-switch-1-socket-6m', 'Full Glass Touch 6 Switch 1 Socket', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 6 Switch (1-25A) 1 Socket (1-10A) (6M).png'),
('full-glass-touch-6-switch-4m', 'Full Glass Touch 6 Switch ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 6 Switch (1-20A) (4M).png'),
('full-glass-touch-8-switch-1-curtain-1-socket-8m', 'Full Glass Touch 8 Switch 1 Curtain 1 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 8 Switch (2-20A) 1 Curtain 1 Socket (1-10A) (8M).png'),
('full-glass-touch-8-switch-1-curtain-6m', 'Full Glass Touch 8 Switch 1 Curtain ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 8 Switch (2-25A) 1 Curtain (6M).png'),
('full-glass-touch-8-switch-1-curtain-8m', 'Full Glass Touch 8 Switch 1 Curtain', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 8 Switch (2-20A) 1 Curtain (8M).png'),
('full-glass-touch-8-switch-1-fan-2-socket-12m', 'Full Glass Touch 8 Switch 1 Fan 2 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 8 Switch (2-25A) 1 Fan 2 Socket (2-10A) (12M).png'),
('full-glass-touch-8-switch-2-fan-2-socket-12m', 'Full Glass Touch 8 Switch 2 Fan 2 Socket ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 8 Switch 2 Fan 2 Socket (2-10A) (12M).png'),
('full-glass-touch-8-switch-4-fan-12m', 'Full Glass Touch 8 Switch 4 Fan ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 8 Switch 4 Fan (12M).png'),
('full-glass-touch-8-switch-4m', 'Full Glass Touch 8 Switch ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch 8 Switch (1-20A) (4M).png'),
('full-glass-touch-fan-2m', 'Full Glass Touch Fan ', 'Full Glass Touch', 0, true, 'products/Full Glass Touch Fan (2M).png'),
('hd-touch-acrylic', 'HD Touch-Acrylic', 'Premium Touch', 0, true, 'products/HD Touch-Acryllic.png'),
('hd-touch-basic', 'HD Touch-Basic', 'Modular Touch', 0, true, 'products/HD Touch-Basic (16A-Relay).png'),
('hd-touch-pro', 'HD Touch-Pro (16A-Relay & RGB Led)', 'Modular Touch', 0, false, 'products/HD Touch-Pro (16A-Relay & RGB Led).png'),
('hd-touch-rf', 'HD Touch-RF (16A-Relay)', 'Premium Touch', 0, false, 'products/HD Touch-RF (16A-Relay).png'),
('led-dimmer-driver-18w', 'LED Dimmer Driver ', 'Smart Lighting', 0, true, 'products/Led dimmer driver (3).jpg'),
('magnetic-3-1fan-hd-1socket-touch', 'Magnetic 3+1Fan+HD+1Socket Touch ', 'Magnetic Touch', 0, false, 'products/Magnetic 3+1Fan+HD+1Socket Touch (6311S).png'),
('magnetic-4-1fan-touch', 'Magnetic 4+1Fan Touch ', 'Magnetic Touch', 0, false, 'products/Magnetic 4+1Fan Touch (4410).png'),
('magnetic-5-1fan-hd-socket-touch', 'Magnetic 5+1Fan+HD+Socket Touch ', 'Magnetic Touch', 0, false, 'products/Magnetic 5+1Fan+HD+Socket Touch (8511S).png'),
('magnetic-7-fan-hd-touch', 'Magnetic 7+Fan+HD Touch ', 'Magnetic Touch', 0, false, 'products/Magnetic 7+Fan+HD Touch (6711).png'),
('magnetic-7-hd-socket-touch', 'Magnetic 7+HD+Socket Touch ', 'Magnetic Touch', 0, false, 'products/Magnetic 7+HD+Socket Touch (6701S).png'),
('magnetic-9-hd-socket-touch', 'Magnetic 9+HD+Socket Touch ', 'Magnetic Touch', 0, false, 'products/Magnetic 9+HD+Socket Touch (8901S).png'),
('metal-touch', 'Metal Touch', 'Premium Touch', 0, false, 'products/Metal Touch.png'),
('microwave-motion-sensor', 'Microwave Motion Sensor', 'Sensors', 0, false, 'products/Microwave Motion Sensor.png'),
('nfc-business-card', 'NFC Business Card', 'Smart QR Products', 0, true, 'products/NFC Business Card.png'),
('nfc-tag-sticker', 'NFC Tag/Sticker', 'Smart QR Products', 0, true, 'products/NFC Tag Sticker.png'),
('pulse-switch-curtain-controller', 'Pulse Switch/Curtain Controller', 'Motorised Products', 0, false, 'products/Pulse Switch Curtain Controller.png'),
('qr-tags', 'QR Tags', 'Smart QR Products', 0, true, 'products/QR Tags.png'),
('rgbw-12v', 'RGBW 12V', 'Strip Controllers', 0, true, 'products/RGBW 12V.png'),
('rgbw-24v', 'RGBW 24V', 'Strip Controllers', 0, true, 'products/RGBW 24V.png'),
('rgbw-controller', 'RGBW Controller (RGBW/CCT)', 'Strip Controllers', 0, true, 'products/RGBW Controller.png'),
('sensor-hub', 'Sensor Hub (Smart IR with Temperature sensor)', 'Sensors', 0, false, 'products/Sensor Hub (Smart IR with Temperature sensor).png'),
('smart-lock-pro-black', 'Smart Lock ', 'Smart Locks', 0, true, 'products/Smart Lock Pro-Black (WiFi).png'),
('smart-lock-pro-silver', 'Smart Lock Pro-Silver', 'Smart Locks', 0, false, 'products/Smart Lock Pro-Silver.png'),
('smart-lock-ultra', 'Smart Lock Ultra', 'Smart Locks', 0, false, 'products/Smart Lock Ultra.png'),
('socket-16a', 'Socket 16A', 'Full Glass Touch', 0, true, 'products/Socket 16A (2M).png');
